PR #36519: [XLA:GPU][oneAPI] Remove change to disable float conversion warning
Imported from GitHub PR https://github.com/openxla/xla/pull/36519

[631797c](https://github.com/openxla/xla/commit/631797c84cbb02e805ec89090214e8093fd8ba1d) commit in XLA caused the following failure in oneAPI GPU build:

`external/org_brotli/c/enc/backward_references_hq.c:199:27: error: implicit conversion between floating point types of different sizes [-Werror,-Wimplicit-float-size-conversion]`

The failure is fixed in rules_ml_toolchain (https://github.com/google-ml-infra/rules_ml_toolchain/pull/172)

This PR removes the extra change added in [631797c](https://github.com/openxla/xla/commit/631797c84cbb02e805ec89090214e8093fd8ba1d) since it is not needed.
Copybara import of the project:

--
8415ebce00dfe6a13aca0b70bf7358643172ef6f by Bhavani Subramanian <bhavani1.subramanian@intel.com>:

Remove change to disable float conversion warning since it is added in rules_ml_toolchain

Merging this change closes #36519

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/36519 from Intel-tensorflow:bhavanis/remove-float-warning 8415ebce00dfe6a13aca0b70bf7358643172ef6f
PiperOrigin-RevId: 858480890